;;; json-par-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from json-par.el

(let ((loads (get 'json-par 'custom-loads))) (if (member '"json-par" loads) nil (put 'json-par 'custom-loads (cons '"json-par" loads)) (put 'json-mode 'custom-loads (cons 'json-par (get 'json-mode 'custom-loads)))))
(autoload 'json-par-mode "json-par" "\
Toggle minor mode for structural editing of JSON.

\\{json-par-mode-map}

This is a minor mode.  If called interactively, toggle the
`Json-Par mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `json-par-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "json-par" '("json-par-"))


;;; Generated autoloads from json-par-ancestor-overlay.el

(register-definition-prefixes "json-par-ancestor-overlay" '("json-par-"))


;;; Generated autoloads from json-par-clone.el

(register-definition-prefixes "json-par-clone" '("json-par-"))


;;; Generated autoloads from json-par-delete.el

(register-definition-prefixes "json-par-delete" '("json-par-"))


;;; Generated autoloads from json-par-fixup.el

(register-definition-prefixes "json-par-fixup" '("json-par-"))


;;; Generated autoloads from json-par-guess.el

(register-definition-prefixes "json-par-guess" '("json-par-"))


;;; Generated autoloads from json-par-indent.el

(register-definition-prefixes "json-par-indent" '("json-par-"))


;;; Generated autoloads from json-par-insert.el

(register-definition-prefixes "json-par-insert" '("json-par-"))


;;; Generated autoloads from json-par-keymap.el

(register-definition-prefixes "json-par-keymap" '("json-par-"))


;;; Generated autoloads from json-par-lexer.el

(register-definition-prefixes "json-par-lexer" '("json-par-"))


;;; Generated autoloads from json-par-mark-narrow.el

(register-definition-prefixes "json-par-mark-narrow" '("json-par-"))


;;; Generated autoloads from json-par-motion.el

(register-definition-prefixes "json-par-motion" '("json-par-"))


;;; Generated autoloads from json-par-oneline-multiline.el

(register-definition-prefixes "json-par-oneline-multiline" '("json-par-"))


;;; Generated autoloads from json-par-raise.el

(register-definition-prefixes "json-par-raise" '("json-par-"))


;;; Generated autoloads from json-par-split-join.el

(register-definition-prefixes "json-par-split-join" '("json-par-"))


;;; Generated autoloads from json-par-transpose.el

(register-definition-prefixes "json-par-transpose" '("json-par-"))


;;; Generated autoloads from json-par-utils.el

(register-definition-prefixes "json-par-utils" '("json-par-"))

;;; End of scraped data

(provide 'json-par-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; json-par-autoloads.el ends here
