;;; pyinspect-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from pyinspect.el

(autoload 'pyinspect-goto-parent-object "pyinspect" "\
Inspect parent object of currently inspected object.
E.g. if we're inspecting `x.y.z', this function switches to buffer `x.y'.
If this objecet has no parent, quit all pyinspect buffers." t)
(autoload 'pyinspect-inspect-at-point "pyinspect" "\
Inspect symbol at point in `pyinspect-mode'." t)
(autoload 'pyinspect-kill-all-buffers "pyinspect" "\
Kill all pyinspect inspection buffers." t)
(autoload 'pyinspect-mode "pyinspect" "\


(fn)" t)
(register-definition-prefixes "pyinspect" '("pyinspect-"))

;;; End of scraped data

(provide 'pyinspect-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pyinspect-autoloads.el ends here
